const eccdeFieldLabels = {
    "schoolCode": "School Code",
    "latitude": "Latitude North",
    "longitude": "Longitude East",
    "elevation": "Elevation (Meter)",
    "schoolName": "A.1 School Name",
    "streetName": "A.2 Number and Street name",
    "villageTown": "A.3 Name of Village or Town",
    "ward": "A.4 Ward",
    "lga": "A.5 LGA",
    "state": "A.6 State",
    "schoolTelephone": "A.7 School Telephone",
    "emailAddress": "A.8 E-mail Address",
    "yearOfEstablishment": "B.1 Year of establishment",
    "location": "B.2 Location",
    "educationLevel": "B.3 Levels of education Offered",
    "schoolType": "B.4 Type of school",
    "shifts": "B.5 Shifts: Does the School operate shift system?",
    "sharedFacilities": "B.6 Shared facilities",
    "howManySchoolsSharing": "If Yes. How many Schools are sharing facilities:",
    "multiGrade": "B.7 Multi-grade teaching",
    "distanceFromCatchment": "B.8 School: Average Distance from Catchment communities (kilometres)",
    "distanceFromLga": "B.9 School: Distance from LGA HQ (kilometres)",
    "pupilsDistance": "B.10 Pupils: Distance from School (pupils further than 3km)",
    "boardingMale": "B.11 Pupils: Boarding - Male",
    "boardingFemale": "B.11 Pupils: Boarding - Female",
    "sdp": "B.12 School Development Plan (SDP)",
    "sbmc": "B.13 School Based Management Committee (SBMC)",
    "pta": "B.14 Parent-Teacher Association (PTA) / Parents' Forum (PF)/ Mother’s Association",
    "lastInspectionDate": "B.15 Date of Last Inspection Visit",
    "inspectionsLastYear": "Number of inspections Visit in last academic year",
    "inspectionAuthority": "B.16 Authority of Last Inspection",
    "conditionalCashTransfer": "B.17 Conditional Cash Transfer (Number of pupils)",
    "grants": "B.18 School Grants",
    "securityGuard": "B.19 Security Guard",
    "ownership": "B.20 Ownership",
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { eccdeFieldLabels };
}