const mongoose = require('mongoose');

const surveySchema = new mongoose.Schema({
    headTeacherName: String,
    contactNumber: String,
    gender: String,
    maritalStatus: String,
    highestQualification: String,
    yearsExperience: Number,
    institutionType: String,
    lgea: String,
    schoolName: String,
    schoolAddress: String,
    location: String,
    latitude: String,
    longitude: String,
    assemblyStart: String,
    assemblyEnd: String,
    teachersMale: Number,
    teachersFemale: Number,
    nonTeachingMale: Number,
    nonTeachingFemale: Number,
    eccdeMale: Number,
    eccdeFemale: Number,
    primaryMale: Number,
    primaryFemale: Number,
    specialMale: Number,
    specialFemale: Number,
    additionalTeachers: Number,
    multigradeClasses: Number,
    multigradeReason: String,

    // Section C
    control_a: String,
    control_b: String,
    cooperation_a: String,
    cooperation_b: String,
    communication_a: String,
    community_a: String,
    supervision_a: String,
    records_a: String,
    health_a: String,

    // Section D
    signboard: String,
    teachersFurnitureAvailable: Number,
    teachersFurnitureGood: Number,
    teachersFurnitureRequired: Number,
    eccdeFurnitureAvailable: Number,
    eccdeFurnitureGood: Number,
    eccdeFurnitureRequired: Number,
    primaryFurnitureAvailable: Number,
    primaryFurnitureGood: Number,
    primaryFurnitureRequired: Number,
    sharedFacility: String,
    perimeterFence: String,
    classroomsAvailable: Number,
    classroomsGood: Number,
    classroomsMinorRepair: Number,
    classroomsMajorRepair: Number,
    classroomsRequired: Number,
    repairDescription: String,
    toiletType: String,
    cubicleAvailable: Number,
    cubicleMinorRepair: Number,
    cubicleMajorRepair: Number,
    cubicleRenovation: Number,
    cubicleRequired: Number,
    toiletRepairDescription: String,
    septicTank: String,
    waterSource: String,
    recommendations: String,
    electricity: String,
    waterlogged: String,
    photos: [String],
    createdAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('Survey', surveySchema);
